// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Oswald, Outfit } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/shared/Header";
// import Footer from "@/components/shared/Footer";
// import ReduxProvider from "@/redux/ReduxProvider";
// import ThemeApplier from "@/components/shared/ThemeApplier";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const oswald = Oswald({
//   subsets: ["latin"],
//   weight: ["200", "300", "400", "500", "600", "700"],
//   variable: "--font-oswald",
// });

// export const outfit = Outfit({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-outfit",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${outfit.variable} antialiased`}
//       >
//         <ReduxProvider>
//           <ThemeApplier />
//           <div className="ratio min-h-screen">
//             <Header />
//             <main className="px-4 md:px-0">
//               {children}
//               <ToastContainer position="top-right" autoClose={1500}/>
//             </main>
//             <Footer />
//           </div>
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }



// src/app/layout.tsx
import type { Metadata } from "next";
import { Oswald, Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import ClientProviders from "@/components/shared/ClientProviders";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-oswald",
  display: "swap", 
  preload: true,
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-outfit",
  display: "swap", 
  preload: true,
});

export const metadata: Metadata = {
  title: {
    default: "ServiceMart — Best Services in Bangladesh",
    template: "%s | ServiceMart",
  },
  description: "ServiceMart — Find the best services and products in Bangladesh at the best price.",
  keywords: ["service", "mart", "bangladesh", "best price", "shopping"],
  authors: [{ name: "ServiceMart" }],
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${oswald.variable} ${outfit.variable} antialiased`}>
        <ReduxProvider>
          <ClientProviders />
          <div className="ratio min-h-screen">
            <Header />
            <main className="px-4 md:px-0">
              {children}
            </main>
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}